CREATE DATABASE COURSE
USE COURSE
CREATE TABLE STUDENTS(
    ID INT PRIMARY KEY IDENTITY,
    FULLNAME NVARCHAR(50) NOT NULL,
    EMAIL NVARCHAR(50) UNIQUE,
    POINT TINYINT CHECK(POINT>=0 AND POINT <=100)

)

SELECT * FROM STUDENTS

INSERT INTO STUDENTS(FULLNAME,EMAIL,POINT)
VALUES
(N'Xədicə Əsədova','xediceasadova@gmail.com',67),
(N'Elmar Qarayev','elmarqarayev@gmail.com',45),
(N'Əfsanə Əsədova','legend@gmail.com',99),
(N'Elnur Qarayev','elnur@gmail.com',34)

SELECT AVG(POINT)  FROM STUDENTS

SELECT *FROM STUDENTS WHERE POINT >(SELECT AVG(POINT) FROM STUDENTS)

SELECT ID,SUBSTRING(FULLNAME,1,CHARINDEX(' ',FULLNAME)-1)AS NAME,POINT FROM STUDENTS

SELECT SUBSTRING(EMAIL, CHARINDEX('@', EMAIL) + 1, LEN(EMAIL)) AS DOMAIN FROM STUDENTS;
